kind: Service
apiVersion: v1
metadata:
  name:  mongodbservice
  namespace: mongo-namespace
spec:
  selector:
    app:  mydb
  type:  ClusterIP
  ports:
  - name:  name-of-the-port
    port:  27017
    targetPort: 27017