apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-deploy
  namespace: mongo-namespace
spec:
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
